//importacion en el eorden que 
//queremos se ejecuten las pruebas
require('./singup_test')
require('./login_test');
require('./getUser_test');
require('./getUserbyId_test');
require('./updateUser_test');
require('./deleteUser_test');
require('./verifyAccount_test');
require('./recoveryPassword_test');
require('./validarToken_test');
require('./updatePassword_test');
require('./suspendAcount_test');
require('./updatePasswordById_test');
require('./loginGoogle_test');
require('./search_test');
//Lynet
require('./registerAlbum_test');
require('./updateAlbum_test');
require('./getAlbum_test');
require('./getAlbumId_test');
require('./getAlbumPage_test');
require('./deleteAlbum_test');
require('./registerArtist_test');
require('./updateArtist_test');
require('./getArtist_test');
require('./getArtistId_test');
require('./getArtistPage_test');
require('./deleteArtist_test');
require('./registerListSong_test');
require('./deleteListSong_test');
//Franco
require('./playlist_test');
require('./song_test');
require('./uploadImage_test');