const express = require('express');
const api = express.Router();
const songController = require('../Controllers/songControllers');
const { ensureAuth } = require('../Middlewares/authenticated');
const { isAdmin } = require('../Middlewares/isAdmin');
const { isMongoId, isValidSong, isValidCollection } = require('../Middlewares/validar-campos');
api.post('/new-song', ensureAuth, isAdmin, isValidSong, songController.songRegister);
api.put('/update-song/:id', ensureAuth, isAdmin, isValidSong, isMongoId, songController.updateSong);
api.delete('/delete-song/:id', ensureAuth, isAdmin, isMongoId, songController.deleteSong);
api.get('/songs', ensureAuth, songController.findSong);
api.get('/get-songs-:collection/:id', ensureAuth, isValidCollection, songController.getSongs);
api.get('/songs/:page', ensureAuth, songController.songsPaginate);
module.exports = api;